### ISSUE TITLE
This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!

### ISSUE THREAD

**Issue by Guillaume-Tnk** [m-muhsin/celestial#9]
Hello sir,

for a project I'm trying to use wordpress and the REST API for the backend and react for the frontend . 
I don't know how to have the react app and the wp-backend on the same domaine name for the visitor to see the react front end as the wordpress index.php will load.
I think that your celestial theme might be the solution, however when I'm running npm install inside celestial theme folder, I'm getting the following error.

Could you help me solve this and tell me if your theme is effectively going to help achieve what I'm trying to?

read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:93:3)
npm ERR! typeerror     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
npm ERR! typeerror     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR! typeerror     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
npm ERR! typeerror     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm ERR! typeerror     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR! typeerror     at processImmediate (timers.js:632:19)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guillaume/.npm/_logs/2019-01-11T14_08_35_446Z-debug.log

**Comment by m-muhsin** [comment]
Yes, this project can help you achieve that!

Can I know what version of Node and NPM you are using?

**Comment by malithmcr** [comment]
@Bare-Guillaume Try to use nvm ( https://github.com/nvm-sh/nvm ) so you can change npm versions or try to remove node_module folder and run again npm install.

**Comment by m-muhsin** [comment]
Thanks @malithmcr 

Closing this issue since there was no activity since January 2019.

**Comment by sdelvalle57** [comment]
try re-opening the console

**Comment by pier0074** [comment]
A bit late, but I came across the same issue and the following command solved it : 
sudo rm -rf node_modules package-lock.json && npm install

**Comment by visenzeviclim** [comment]
8 months later since 22 Oct 2020, @pier0074 's solution still works !!!

**Comment by Akinolae** [comment]
Gracias

**Comment by jahanzaibijaz** [comment]
@pier0074 would it work on angular project?

**Comment by jahanzaibijaz** [comment]
> 8 months later since 22 Oct 2020, @pier0074 's solution still works !!!

@visenzeviclim for angular project ?

**Comment by fono97** [comment]
thanks 
I was having the same pb 
I just remove the node_module and then install npm to generate the new node_module and things correctly

**Comment by lk77** [comment]
npm rebuild does that too

**Comment by best-lucky1030** [comment]
> A bit late, but I came across the same issue and the following command solved it :

@pier0074
It works on Win OS?
I have same problem on Win.
I tried to reinstall node modules after removed `node_modules` and `package-lock.json`, but it was same. ;(
There is no solution here?

**Comment by pier0074** [comment]
> > A bit late, but I came across the same issue and the following command solved it :
> 
> @pier0074 It works on Win OS? I have same problem on Win. I tried to reinstall node modules after removed `node_modules` and `package-lock.json`, but it was same. ;( There is no solution here?

Nope, it was on MacOS but it should be working as well.

I do not know the equivalent cmd line in WinOS for removing folder and files but doing manually should work. 
Maybe make sure you empty the recycle bin as it's done manually ?! 
After deleting the folder `node_modules` and the file `package-lock.json` try and relaunch the cmd `npm install` as explained above.

**Comment by olexandr13** [comment]
I have updated npm from 6 to 8 and it helps.
`npm install -g npm@latest`
(Update to version 7 also should help).

Deleting `package-lock` is not the best solution...

**Comment by alanthssss** [comment]
> I have updated npm from 6 to 8 and it helps. `npm install -g npm@latest` (Update to version 7 also should help).
> 
> Deleting `package-lock` is not the best solution...

It works for me, thank you! @olexandr13

**Comment by kinginthenorthcodez** [comment]
@pier0074  Thanks , running ```sudo rm -rf node_modules package-lock.json && npm install ``` . solved my issues of ''
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!"

**Comment by alvin-milton** [comment]
you only need to run (after installing the right version of node):
1. `rm package-lock.json` 
2. `npm i`

**Comment by AlexandreDurazzo** [comment]
> I have updated npm from 6 to 8 and it helps. `npm install -g npm@latest` (Update to version 7 also should help).

That worked, thank you!!

**Comment by IagoBarboza** [comment]
Still working!
